[package]
name = "set_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alfred-workflow-rust-project = { path = "../../../alfred-workflow-rust-project" }